Add Rigetti Provider Documentation
MicrosoftDocs/quantum-docs pull request #563
Opened 2022-09-01 03:01 UTC by kalzoo

This includes:

- Main Rigetti documentation
- Support documentation
- Pricing information

2022-09-01 03:02 UTC, tedhudek commented
Docs Build status updates of commit _[41402b0](https://github.com/rigetti/microsoft-azure-quantum-docs/commits/41402b03625ed267d0b873dbf7266839b53fd6d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[articles/provider-rigetti.md](https://github.com/rigetti/microsoft-azure-quantum-docs/blob/feat/rigetti-provider/articles/provider-rigetti.md) | :bulb:Suggestion | | [Details](#user-content-514026d2fff7346a88e1f71d3a400d98-507d22ab)
[articles/provider-support-rigetti.md](https://github.com/rigetti/microsoft-azure-quantum-docs/blob/feat/rigetti-provider/articles/provider-support-rigetti.md) | :bulb:Suggestion | | [Details](#user-content-e5c5a2b0df7d907df261bc8920be51c3-507d22ab)
[articles/includes/pricing-qc.md](https://github.com/rigetti/microsoft-azure-quantum-docs/blob/feat/rigetti-provider/articles/includes/pricing-qc.md) | :white_check_mark:Succeeded | |

<a id="514026d2fff7346a88e1f71d3a400d98-507d22ab"></a>
### [articles/provider-rigetti.md](https://github.com/rigetti/microsoft-azure-quantum-docs/blob/feat/rigetti-provider/articles/provider-rigetti.md)
 - **Line 4, Column 12**: **[Suggestion: ms-author-invalid - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'kalzoo' is not a valid Microsoft alias.`````

<a id="e5c5a2b0df7d907df261bc8920be51c3-507d22ab"></a>
### [articles/provider-support-rigetti.md](https://github.com/rigetti/microsoft-azure-quantum-docs/blob/feat/rigetti-provider/articles/provider-support-rigetti.md)
 - **Line 4, Column 12**: **[Suggestion: ms-author-invalid - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'kalzoo' is not a valid Microsoft alias.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/776a9f04-28cf-7639-37fb-77d3aae09b34/202209010301154347-563/BuildReport?accessString=03cda9eec44d197fcba46a993475924ba35f5251b75da470b98d420b05d26faf).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/776a9f04-28cf-7639-37fb-77d3aae09b34?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-01 03:05 UTC, tedhudek commented
Docs Build status updates of commit _[0fda156](https://github.com/rigetti/microsoft-azure-quantum-docs/commits/0fda1561709219fb109bce05196f54b5ba85719a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[articles/provider-rigetti.md](https://github.com/rigetti/microsoft-azure-quantum-docs/blob/feat/rigetti-provider/articles/provider-rigetti.md) | :warning:Warning | | [Details](#user-content-514026d2fff7346a88e1f71d3a400d98-a54a02f4)
[articles/provider-support-rigetti.md](https://github.com/rigetti/microsoft-azure-quantum-docs/blob/feat/rigetti-provider/articles/provider-support-rigetti.md) | :warning:Warning | | [Details](#user-content-e5c5a2b0df7d907df261bc8920be51c3-a54a02f4)
[articles/includes/pricing-qc.md](https://github.com/rigetti/microsoft-azure-quantum-docs/blob/feat/rigetti-provider/articles/includes/pricing-qc.md) | :white_check_mark:Succeeded | |

<a id="514026d2fff7346a88e1f71d3a400d98-a54a02f4"></a>
### [articles/provider-rigetti.md](https://github.com/rigetti/microsoft-azure-quantum-docs/blob/feat/rigetti-provider/articles/provider-rigetti.md)
 - **Line 2, Column 1**: **[Warning: ms-author-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="e5c5a2b0df7d907df261bc8920be51c3-a54a02f4"></a>
### [articles/provider-support-rigetti.md](https://github.com/rigetti/microsoft-azure-quantum-docs/blob/feat/rigetti-provider/articles/provider-support-rigetti.md)
 - **Line 2, Column 1**: **[Warning: ms-author-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/776a9f04-28cf-7639-37fb-77d3aae09b34/202209010304275347-563/BuildReport?accessString=dedd52a4467fbde4da3b6f1c087547a4a1ae94c92803ad411f545212994e7b32).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/776a9f04-28cf-7639-37fb-77d3aae09b34?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-01 03:07 UTC, kalzoo commented
The 🤖 doesn't like having no `ms.author` nor having my name in there, and clicking on the link results in this: 
![image](https://user-images.githubusercontent.com/22137047/187823545-d036d416-3351-453f-860f-5e7d6fccdc6a.png)

@tedhudek, lmk what you'd like in that header field.

2022-09-01 16:07 UTC, Jak-MS commented
@MicrosoftDocs/quantum_docs_writers @tedhudek - 
- Can you review this PR?
- Note that since it contains new content, the PR would need to be moved to the private repo and someone on the quantum docs team would need to take ownership.


IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2022-09-01 18:16 UTC, Bradben commented
@kalzoo - Thanks for helping out with the Rigetti content! I updated the metadata so you shouldn't be getting that warning anymore. I'll be editing the content to get it ready for publishing but ping me if you have any questions along the way. 

One other article that might need updating is this page - https://docs.microsoft.com/en-us/azure/quantum/quantum-computing-target-profiles. Can you review and see what applies to Rigetti or what new content may be needed? 

Thanks - Brad

2022-09-01 18:17 UTC, Bradben commented on articles/provider-rigetti.md
> +author: kalzoo
```suggestion
author: kalzoo
ms.author: brbenefield
```

2022-09-01 18:17 UTC, Bradben commented on articles/provider-support-rigetti.md
> +author: kalzoo
```suggestion
author: kalzoo
ms.author: brbenefield
```

2022-09-06 16:28 UTC, tedhudek commented
Docs Build status updates of commit _[32b52fd](https://github.com/rigetti/microsoft-azure-quantum-docs/commits/32b52fd6024217f7e3865860dc4007284bb8a91a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[articles/includes/pricing-qc.md](https://github.com/rigetti/microsoft-azure-quantum-docs/blob/feat/rigetti-provider/articles/includes/pricing-qc.md) | :white_check_mark:Succeeded | |
[articles/provider-rigetti.md](https://github.com/rigetti/microsoft-azure-quantum-docs/blob/feat/rigetti-provider/articles/provider-rigetti.md) | :white_check_mark:Succeeded | |
[articles/provider-support-rigetti.md](https://github.com/rigetti/microsoft-azure-quantum-docs/blob/feat/rigetti-provider/articles/provider-support-rigetti.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/776a9f04-28cf-7639-37fb-77d3aae09b34/202209061627319437-563/BuildReport?accessString=a8b5ede51e117ecf1cfe03e14992417421c02bb9158028fe01090fea6cd980e6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/776a9f04-28cf-7639-37fb-77d3aae09b34?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-06 20:23 UTC, tedhudek commented
Docs Build status updates of commit _[f82d16a](https://github.com/rigetti/microsoft-azure-quantum-docs/commits/f82d16a115cd9e9a2a7518b425c73a30f5092731)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[articles/includes/pricing-qc.md](https://github.com/rigetti/microsoft-azure-quantum-docs/blob/feat/rigetti-provider/articles/includes/pricing-qc.md) | :white_check_mark:Succeeded | |
[articles/provider-rigetti.md](https://github.com/rigetti/microsoft-azure-quantum-docs/blob/feat/rigetti-provider/articles/provider-rigetti.md) | :white_check_mark:Succeeded | |
[articles/provider-support-rigetti.md](https://github.com/rigetti/microsoft-azure-quantum-docs/blob/feat/rigetti-provider/articles/provider-support-rigetti.md) | :white_check_mark:Succeeded | |
[articles/quantum-computing-target-profiles.md](https://github.com/rigetti/microsoft-azure-quantum-docs/blob/feat/rigetti-provider/articles/quantum-computing-target-profiles.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/776a9f04-28cf-7639-37fb-77d3aae09b34/202209062022218260-563/BuildReport?accessString=810700b8177e40296aecdc2603f74fc8ad8261b073b365bafaf3cb1213eff2ce).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/776a9f04-28cf-7639-37fb-77d3aae09b34?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-07 05:26 UTC, Bradben requested changes
Minor copy edits and formatting standards - it looks good, thanks!

2022-09-07 05:26 UTC, Bradben commented on articles/provider-rigetti.md
> +[QVM is an open-source simulator][QVM] for [Quil]. The `rigetti.sim.qvm` target accepts a [Quil] program as text and runs that program on [QVM] hosted in the cloud, returning simulated results.
```suggestion
[QVM] is an open-source simulator for [Quil]. The `rigetti.sim.qvm` target accepts a Quil program as text and runs that program on QVM hosted in the cloud, returning simulated results.
```

2022-09-07 05:26 UTC, Bradben commented on articles/provider-rigetti.md
> +To make constructing a [Quil] program easier, you can use [`pyQuil`] along with the [`pyquil-for-azure-quantum`] package. Without this package, [`pyQuil`] can be used to _construct_ Quil programs but
```suggestion
All Rigetti targets accept the `rigetti.quil.v1` input format, which is the text of a [Quil] program. By default, the program will be compiled using [quilc] before running. However, quilc does not support the pulse level control features ([Quil-T]), so if you want to use those features you must provide a [Native Quil] program (also containing Quil-T) as input and specify the `skipQuilc` input parameter.

To make constructing a Quil program easier, you can use [`pyQuil`] along with the [`pyquil-for-azure-quantum`] package. Without this package, `pyQuil` can be used to _construct_ Quil programs but not submit them to Azure Quantum.
```

2022-09-07 05:26 UTC, Bradben commented on articles/provider-rigetti.md
> +
```suggestion
***

```

2022-09-07 05:26 UTC, Bradben commented on articles/provider-support-rigetti.md
> +This article describes the Microsoft support policy that applies when you use the Rigetti provider in Azure Quantum. The article applies to any of the targets under this provider.
```suggestion
This article describes the Microsoft support policy that applies when you use the Rigetti provider in Azure Quantum. The article applies to any of the [targets](xref:microsoft.quantum.providers.rigetti#targets) offered by the Rigetti provider.
```

2022-09-07 05:26 UTC, Bradben commented on articles/provider-support-rigetti.md
> +If you're using the Rigetti provider and experience unexpected issues, you can contact the Azure Support team for help
```suggestion
If you're using the Rigetti provider and experience unexpected issues, you can contact the Azure Support team for help.
```

2022-09-07 05:26 UTC, Bradben commented on articles/provider-support-rigetti.md
> +"Business days" are defined as Monday through Friday, not counting US holidays. Example: if a medium-severity incident is reported on a Tuesday, a response will be returned by the end of the business
```suggestion
*Business days* are defined as Monday through Friday, not counting US holidays. For example, if a medium-severity incident is reported on a Tuesday, a response will be returned by the end of the business day on Thursday, if the intervening days are also business days.
```

2022-09-07 05:26 UTC, Bradben commented on articles/provider-rigetti.md
> +The easiest way to submit Quil jobs is using the [`pyquil-for-azure-quantum`] package, as it allows you to leverage the tools and documentation of the [`pyQuil`] library.
```suggestion
The easiest way to submit Quil jobs is using the [`pyquil-for-azure-quantum`] package, as it allows you to leverage the tools and documentation of the [`pyQuil`] library.

You can also construct Quil programs manually and submit them using the `azure-quantum` package directly.
```

2022-09-07 17:16 UTC, Bradben commented
@kalzoo - do you have time to look at and commit these changes today? Thanks!

2022-09-07 19:13 UTC, kalzoo commented on articles/provider-rigetti.md
> +In addition to the Azure Quantum Credits plan, Rigetti offers a pay-as-you-go plan for live quantum processors, so you pay only for what you use.
```suggestion
To see Rigetti's billing plan, visit [Azure Quantum pricing](xref:microsoft.quantum.providers-pricing).
```

2022-09-07 19:16 UTC, kalzoo commented on articles/provider-rigetti.md
> +All of Rigetti's [publicly available QPUs](https://qcs.rigetti.com/qpus) are available through Azure Quantum. QPU targets optionally take a `skipQuilc` parameter for skipping the default compilation
```suggestion
All of Rigetti's [publicly available QPUs](https://qcs.rigetti.com/qpus) are available through Azure Quantum. Note that this list is subject to frequent change over time without advance notice.
```

2022-09-07 19:18 UTC, kalzoo commented on articles/provider-rigetti.md
> +To make constructing a [Quil] program easier, you can use [`pyQuil`] along with the [`pyquil-for-azure-quantum`] package. Without this package, [`pyQuil`] can be used to _construct_ Quil programs but
```suggestion
All Rigetti targets accept the `rigetti.quil.v1` input format, which is the text of a [Quil] program. By default, the program will be compiled using [quilc] before running. However, quilc does not support the pulse level control features ([Quil-T]), so if you want to use those features you must provide a [Native Quil] program (also containing Quil-T) as input and specify the input parameter `skipQuilc: true`.
	
To make constructing a Quil program easier, you can use [`pyQuil`] along with the [`pyquil-for-azure-quantum`] package. Without this package, `pyQuil` can be used to _construct_ Quil programs but not submit them to Azure Quantum.
```

2022-09-07 19:19 UTC, kalzoo commented
@Bradben done - accepted most as-is, tweaked a couple. Thanks!

2022-09-07 19:19 UTC, tedhudek commented
Docs Build status updates of commit _[39cb3ee](https://github.com/rigetti/microsoft-azure-quantum-docs/commits/39cb3ee375cebca8ac1b821ab8ee7b329c9d6e8e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[articles/includes/pricing-qc.md](https://github.com/rigetti/microsoft-azure-quantum-docs/blob/feat/rigetti-provider/articles/includes/pricing-qc.md) | :white_check_mark:Succeeded | |
[articles/provider-rigetti.md](https://github.com/rigetti/microsoft-azure-quantum-docs/blob/feat/rigetti-provider/articles/provider-rigetti.md) | :white_check_mark:Succeeded | |
[articles/provider-support-rigetti.md](https://github.com/rigetti/microsoft-azure-quantum-docs/blob/feat/rigetti-provider/articles/provider-support-rigetti.md) | :white_check_mark:Succeeded | |
[articles/quantum-computing-target-profiles.md](https://github.com/rigetti/microsoft-azure-quantum-docs/blob/feat/rigetti-provider/articles/quantum-computing-target-profiles.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/776a9f04-28cf-7639-37fb-77d3aae09b34/202209071918518409-563/BuildReport?accessString=f900dc0fe6506a834810163da161202e7d29aafcb3acd18f78aa6414afbc74c6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/776a9f04-28cf-7639-37fb-77d3aae09b34?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-07 19:33 UTC, Bradben approved these changes

2022-09-07 21:08 UTC, Bradben commented
Moved to private repo for testing and verification.

2022-09-07 21:08 UTC, closed without merging